name: student
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6                 # For making HTTP requests
  image_picker: ^0.8.7+4        # For picking images from gallery/camera
  flutter_markdown: ^0.6.11     # For rendering markdown formatted feedback report

  
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
